#!/bin/bash

echo "🚀 Revora Project - Quick Deploy Script"
echo "======================================"
echo ""
echo "This script will help you deploy to Netlify quickly!"
echo ""
echo "📋 PRE-DEPLOYMENT CHECKLIST:"
echo "✅ Code is committed to GitHub"
echo "✅ Build works locally"
echo "✅ Netlify configuration ready"
echo ""
echo "🌐 DEPLOYMENT STEPS:"
echo "1. Go to: https://netlify.com"
echo "2. Sign up/Login with GitHub"
echo "3. Click 'New site from Git'"
echo "4. Select: AbdullahYaseen01/RevoraProject"
echo "5. Click 'Deploy site'"
echo ""
echo "⚙️  ENVIRONMENT VARIABLES TO ADD:"
echo "Copy these to Netlify → Site Settings → Environment Variables:"
echo ""
echo "NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoicmV2YXJhYWkiLCJhIjoiY21iODdhMzJ4MDBnczJtcHd2NXpibW1laSJ9.e6-3MRdJxZaLUxoUUSEFcg"
echo "NEXT_PUBLIC_MAPBOX_STYLE=mapbox://styles/mapbox/streets-v12"
echo "DATABASE_URL=postgresql://username:password@localhost:5432/revara_db"
echo "NEXTAUTH_URL=https://your-site-name.netlify.app"
echo "NEXTAUTH_SECRET=your-super-secret-key-here"
echo "STRIPE_PUBLISHABLE_KEY=pk_test_your_test_key"
echo "STRIPE_SECRET_KEY=sk_test_your_test_key"
echo ""
echo "🎯 Your site will be live at: https://random-name.netlify.app"
echo ""
echo "📚 For detailed instructions, see: DEPLOYMENT_GUIDE.md"
echo ""
echo "✨ Happy deploying!"
